In [1]:
import numpy as np
import torch

In [2]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([[2,3], [4, 5]])
zeros = torch.zeros(2,3)
ones = torch.ones(2,3)
rand = torch.rand(2,3)
eye = torch.eye(3)

In [4]:
print(t1)
print(t2)
print(zeros)
print(ones)
print(rand)
print(eye)

tensor([1, 2, 3])
tensor([[2, 3],
        [4, 5]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0887, 0.1804, 0.9772],
        [0.6394, 0.5718, 0.2112]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
